<?php
$id = (int) $ordem['id_ordem'];
$numero = $ordem['numero'] ?: 'Atendimento #' . $id;
$status = $ordem['status_operacional'];
$cancelado = $status === 'cancelado';
$cliente = $ordem['cliente'] ?? [];
$totais = $ordem['totais'];
$financeiro = $ordem['financeiro'];
$moeda = static fn ($v) => 'R$ ' . number_format((float) $v, 2, ',', '.');
$medida = static fn ($v) => rtrim(rtrim(number_format((float) $v, 4, ',', '.'), '0'), ',');
$dataBr = static fn ($v, $hora = false) => empty($v) || str_starts_with($v, '0000') ? '—' : date($hora ? 'd/m/Y H:i' : 'd/m/Y', strtotime($v));
$hidden = static fn () => csrf_field() . '<input type="hidden" name="id_ordem" value="' . $id . '">';
$chave = static fn () => '<input type="hidden" name="chave_operacao" value="' . bin2hex(random_bytes(24)) . '">';
$arte = ['nao_necessita' => 'Não necessita de arte', 'cliente' => 'Arte do cliente', 'grafica' => 'Arte feita pela gráfica'];
$tipos = ['fixo' => 'Preço fixo', 'unidade' => 'Por unidade', 'metro_linear' => 'Por metro linear', 'metro_quadrado' => 'Por m²', 'quantidade' => 'Por quantidade / lote'];
?>
<div class="content-wrapper"><section class="content pt-3"><div class="container-fluid">
<div class="d-flex justify-content-between align-items-center flex-wrap mb-3"><div><h1 class="h4 mb-1"><?= esc($numero) ?></h1><span class="badge badge-<?= $cancelado ? 'secondary' : ($status === 'concluido' ? 'success' : 'info') ?>"><?= esc($statuses[$status]) ?></span><span class="text-muted small ml-2">Criado em <?= $dataBr($ordem['created_at'], true) ?></span></div><div class="mt-2"><a class="btn btn-outline-secondary" href="/ordensDeServicos/orcamentos?todos=1">Voltar</a> <a class="btn btn-outline-primary" href="/ordensDeServicos/imprimirAtendimento/<?= $id ?>" target="_blank" rel="noopener"><i class="fas fa-print" aria-hidden="true"></i> Imprimir / PDF</a> <a class="btn btn-primary" href="/ordensDeServicos/edit/<?= $id ?>">Editar orçamento</a></div></div>
<?php foreach (['atendimento_sucesso' => 'success', 'atendimento_erro' => 'danger'] as $key => $color): if ($message = session()->getFlashdata($key)): ?><div class="alert alert-<?= $color ?>" role="alert"><?= esc($message) ?></div><?php endif; endforeach ?>
<div class="row"><div class="col-lg-8"><div class="card"><div class="card-body"><h2 class="h5"><?= esc(($cliente['tipo'] ?? 1) != 1 && ! empty($cliente['razao_social']) ? $cliente['razao_social'] : ($cliente['nome'] ?? 'Cliente')) ?></h2><p class="text-muted mb-2"><?= esc(implode(' · ', array_filter(array_unique([$cliente['whatsapp'] ?? '', $cliente['celular'] ?? '', $cliente['telefone_fixo'] ?? '', $cliente['email'] ?? ''])))) ?></p><a class="small" href="/clientes/show/<?= (int) $ordem['id_cliente'] ?>">Ver cadastro do cliente</a><hr><div class="row">
<?php foreach (['atendente' => 'Atendente', 'vendedor' => 'Vendedor', 'tecnico' => 'Técnico'] as $key => $label): $pessoa = $ordem[$key] ?? []; ?><div class="col-sm-4 d-flex align-items-center mb-2"><?php if (! empty($pessoa['foto']) && ! preg_match('#(?:\.\.|^[a-z]+:|^//)#i', $pessoa['foto'])): ?><img src="<?= esc(base_url($pessoa['foto']), 'attr') ?>" class="rounded-circle mr-2" style="width:40px;height:40px;object-fit:cover" alt=""><?php endif ?><div><small class="text-muted d-block"><?= $label ?></small><?= esc($pessoa['primeiro_nome'] ?? $pessoa['nome'] ?? ($key === 'tecnico' ? 'A definir' : 'Não informado')) ?></div></div><?php endforeach ?>
</div></div></div></div><div class="col-lg-4"><div class="card"><div class="card-body"><div class="d-flex justify-content-between"><span>Total do orçamento</span><strong><?= $moeda($totais['total']) ?></strong></div><div class="d-flex justify-content-between text-success my-2"><span>Recebido</span><strong><?= $moeda($financeiro['pago']) ?></strong></div><div class="d-flex justify-content-between border-top pt-2"><span>Saldo a receber</span><strong class="h5 mb-0"><?= $moeda($financeiro['saldo']) ?></strong></div><?php if (! empty($ordem['entrada_necessaria'])): ?><p class="small mb-0 mt-2">Entrada combinada: <?= $moeda($ordem['valor_entrada']) ?> · <?= bccomp($financeiro['pago'], $ordem['valor_entrada'], 2) >= 0 ? 'Recebida' : 'Pendente' ?></p><?php endif ?></div></div></div></div>
<div class="card"><div class="card-header"><h2 class="card-title">Andamento</h2></div><div class="card-body">
<?php if ($cancelado): ?><p>Atendimento cancelado. Pagamentos e consumos anteriores permanecem no histórico.</p><form method="post" action="/ordensDeServicos/reabrirAtendimento"><?= $hidden() ?><label for="reabertura">Observação da reabertura</label><input class="form-control mb-2" id="reabertura" name="observacoes" maxlength="2048"><button class="btn btn-primary" type="submit">Reabrir atendimento</button></form>
<?php else: ?><form class="row align-items-end" method="post" action="/ordensDeServicos/statusAtendimento"><?= $hidden() ?><div class="form-group col-md-4"><label for="novo-status">Situação</label><select class="form-control" name="status_operacional" id="novo-status"><?php foreach ($statuses as $key => $label): if ($key === 'cancelado') continue; ?><option value="<?= esc($key, 'attr') ?>" <?= $key === $status ? 'selected' : '' ?>><?= esc($label) ?></option><?php endforeach ?></select></div><div class="form-group col-md-6"><label for="observacao-status">Observação <small>(opcional)</small></label><input class="form-control" id="observacao-status" name="observacoes" maxlength="2048"></div><div class="form-group col-md-2"><button class="btn btn-primary" type="submit">Atualizar</button></div></form>
<?php endif ?><div class="small text-muted">Validade: <?= $dataBr($ordem['validade_orcamento']) ?> · Previsão de conclusão: <?= $dataBr($ordem['previsao_conclusao']) ?></div>
</div></div>
<div class="card"><div class="card-header"><h2 class="card-title">Serviços e cortesias</h2></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Serviço</th><th>Quantidade e medidas</th><th>Execução</th><th class="text-right">Preço</th><th class="text-right">Subtotal</th></tr></thead><tbody>
<?php foreach ($ordem['itens'] as $item): ?><tr class="<?= ! empty($item['cortesia']) ? 'table-light' : '' ?>"><td><strong><?= esc($item['nome']) ?></strong><?php if (! empty($item['cortesia'])): ?> <span class="badge badge-success">Cortesia</span><?php endif ?><small class="d-block text-muted"><?= nl2br(esc($item['descricao'] ?? '')) ?></small></td><td><?= $medida($item['quantidade']) ?> <?= esc($item['unidade']) ?><?php if (! empty($item['largura'])): ?><small class="d-block"><?= $medida($item['largura']) ?><?= ! empty($item['altura']) ? ' × ' . $medida($item['altura']) : '' ?> <?= esc($item['unidade_dimensao']) ?></small><?php endif ?><?php if (! empty($item['area'])): ?><small><?= $medida($item['area']) ?> m² por peça</small><?php endif ?></td><td><?= esc(ucfirst($item['tipo_execucao'])) ?><small class="d-block"><?= esc($arte[$item['arte']] ?? $item['arte']) ?></small><?php if (! empty($item['necessita_instalacao'])): ?><small>Com instalação</small><?php endif ?></td><td class="text-right text-nowrap"><?= $moeda($item['valor']) ?><small class="d-block text-muted"><?= esc($tipos[$item['tipo_preco']] ?? '') ?></small></td><td class="text-right text-nowrap"><strong><?= $moeda($item['total']) ?></strong></td></tr><?php endforeach ?>
</tbody></table></div><div class="card-body border-top"><div class="row"><div class="col-md-8"><?php if (! empty($ordem['observacoes'])): ?><strong>Observações para o cliente</strong><p><?= nl2br(esc($ordem['observacoes'])) ?></p><?php endif ?><?php if (! empty($ordem['observacoes_internas'])): ?><details><summary>Observações internas</summary><p class="mt-2"><?= nl2br(esc($ordem['observacoes_internas'])) ?></p></details><?php endif ?></div><div class="col-md-4"><div class="d-flex justify-content-between"><span>Subtotal</span><span><?= $moeda($totais['subtotal']) ?></span></div><div class="d-flex justify-content-between"><span>Desconto</span><span>− <?= $moeda($totais['desconto']) ?></span></div><?php if (! empty($ordem['desconto_motivo'])): ?><small class="text-muted"><?= esc($ordem['desconto_motivo']) ?></small><?php endif ?><?php foreach (['frete' => 'Frete', 'outros' => 'Outros acréscimos'] as $key => $label): if (bccomp($totais[$key], '0', 2) > 0): ?><div class="d-flex justify-content-between"><span><?= $label ?></span><span><?= $moeda($totais[$key]) ?></span></div><?php endif; endforeach ?><div class="d-flex justify-content-between border-top mt-2 pt-2"><strong>Total</strong><strong><?= $moeda($totais['total']) ?></strong></div></div></div></div></div>
<div class="card" id="pagamentos"><div class="card-header"><h2 class="card-title">Pagamento</h2></div><div class="card-body"><div class="row"><div class="col-lg-5"><h3 class="h6">Condições combinadas</h3><p><?= nl2br(esc($ordem['condicao_pagamento'] ?: 'Conforme parcelas abaixo.')) ?></p><table class="table table-sm"><thead><tr><th>Forma</th><th>Vencimento</th><th class="text-right">Valor</th></tr></thead><tbody><?php foreach ($ordem['parcelas'] as $p): ?><tr><td><?= esc($p['forma_de_pagamento']) ?></td><td><?= $dataBr($p['data_de_vencimento']) ?></td><td class="text-right"><?= $moeda($p['valor_da_parcela']) ?></td></tr><?php endforeach ?></tbody></table></div><div class="col-lg-7"><h3 class="h6">Recebimentos realizados</h3><?php if (! $financeiro['recebimentos']): ?><p class="text-muted">Nenhum recebimento registrado.</p><?php endif ?>
<?php foreach ($financeiro['recebimentos'] as $r): $estornado = ! empty($r['estornado_at']); ?><div class="border rounded p-2 mb-2"><div class="d-flex justify-content-between"><span><?= esc($r['forma_de_pagamento']) ?> · <?= $dataBr($r['created_at'], true) ?></span><strong><?= $moeda($r['valor']) ?></strong></div><?php if ($estornado): ?><small class="text-muted">Estornado em <?= $dataBr($r['estornado_at'], true) ?>: <?= esc($r['estorno_motivo']) ?></small><?php else: ?><details class="mt-1"><summary class="small text-muted">Estornar recebimento</summary><form class="mt-2" method="post" action="/ordensDeServicos/estornarRecebimentoAtendimento"><?= $hidden() ?><input type="hidden" name="id_recebimento" value="<?= (int) $r['id_pagamento'] ?>"><label class="small" for="estorno-rec-<?= (int) $r['id_pagamento'] ?>">Motivo do estorno</label><input class="form-control form-control-sm mb-2" id="estorno-rec-<?= (int) $r['id_pagamento'] ?>" name="motivo" required maxlength="512"><button class="btn btn-sm btn-outline-danger" type="submit">Confirmar estorno</button></form></details><?php endif ?></div><?php endforeach ?>
<?php if (! $cancelado && bccomp($financeiro['saldo'], '0', 2) > 0): ?><details class="border rounded p-3 mt-3"><summary class="text-primary font-weight-bold">Registrar recebimento</summary><form class="mt-3" method="post" action="/ordensDeServicos/receberAtendimento"><?= $hidden() ?><?= $chave() ?><div class="row"><div class="form-group col-sm-4"><label for="valor-recebido">Valor recebido</label><input class="form-control" id="valor-recebido" name="valor" inputmode="decimal" required placeholder="0,00"></div><div class="form-group col-sm-4"><label for="forma-recebida">Forma</label><select class="form-control" id="forma-recebida" name="forma_de_pagamento" required><option value="">Selecione</option><?php foreach ($formas as $f): ?><option value="<?= esc($f['nome'], 'attr') ?>"><?= esc($f['nome']) ?></option><?php endforeach ?></select></div><div class="form-group col-sm-4"><label for="caixa-recebido">Caixa <small>(opcional)</small></label><select class="form-control" name="id_caixa" id="caixa-recebido"><option value="">Sem caixa</option><?php foreach ($caixas as $caixa): ?><option value="<?= (int) $caixa['id_caixa'] ?>">Caixa #<?= (int) $caixa['id_caixa'] ?></option><?php endforeach ?></select></div></div><div class="form-group"><label for="parcela-recebida">Vincular à parcela <small>(opcional)</small></label><select class="form-control" name="id_parcela" id="parcela-recebida"><option value="">Pagamento geral / entrada</option><?php foreach ($ordem['parcelas'] as $p): ?><option value="<?= (int) $p['id_parcela'] ?>"><?= $dataBr($p['data_de_vencimento']) ?> · <?= esc($p['forma_de_pagamento']) ?> · <?= $moeda($p['valor_da_parcela']) ?></option><?php endforeach ?></select></div><div class="form-group"><label for="obs-recebimento">Observação</label><input class="form-control" id="obs-recebimento" name="observacoes" maxlength="512"></div><button class="btn btn-primary" type="submit">Confirmar recebimento</button></form></details><?php endif ?>
</div></div></div></div>
<?php if (! empty($ordem['execucao_endereco'])): ?><div class="card"><div class="card-header"><h2 class="card-title">Execução externa / instalação</h2></div><div class="card-body"><p><?= nl2br(esc($ordem['execucao_endereco'])) ?><br><?= esc($ordem['execucao_referencia']) ?></p><p>Agendamento: <?= $dataBr($ordem['execucao_prevista'], true) ?><br>Responsável no local: <?= esc($ordem['execucao_responsavel']) ?> · <?= esc($ordem['execucao_telefone']) ?></p><?= nl2br(esc($ordem['execucao_observacoes'])) ?></div></div><?php endif ?>
<div class="card"><div class="card-header"><h2 class="card-title">Arquivos e fotos</h2></div><div class="card-body"><div class="row"><?php foreach ($ordem['anexos'] as $a): ?><div class="col-md-4 mb-3"><a href="/ordensDeServicos/baixarAnexoAtendimento/<?= (int) $a['id_anexo'] ?>"><?= esc($a['nome']) ?></a><small class="d-block text-muted"><?= esc(\App\Libraries\AnexoAtendimento::CATEGORIAS[$a['categoria']] ?? $a['categoria']) ?> · <?= $dataBr($a['created_at']) ?></small></div><?php endforeach ?></div><?php if (! $ordem['anexos']): ?><p class="text-muted">Nenhum arquivo anexado.</p><?php endif ?>
<?php if (! $cancelado): ?><details><summary class="text-primary">Anexar arquivo ou foto</summary><form class="mt-3" method="post" enctype="multipart/form-data" action="/ordensDeServicos/anexarAtendimento"><?= $hidden() ?><div class="row"><div class="form-group col-md-5"><label for="arquivo-atendimento">Arquivo</label><input class="form-control-file" type="file" id="arquivo-atendimento" name="arquivo" accept=".pdf,.jpg,.jpeg,.png,.webp" required><small class="text-muted">PDF, JPG, PNG ou WEBP, até 20 MB.</small></div><div class="form-group col-md-3"><label for="categoria-arquivo">Categoria</label><select class="form-control" name="categoria" id="categoria-arquivo"><?php foreach (\App\Libraries\AnexoAtendimento::CATEGORIAS as $key => $label): ?><option value="<?= esc($key, 'attr') ?>"><?= esc($label) ?></option><?php endforeach ?></select></div><div class="form-group col-md-4"><label for="servico-arquivo">Serviço <small>(opcional)</small></label><select class="form-control" name="id_servico_os" id="servico-arquivo"><option value="">Atendimento completo</option><?php foreach ($ordem['itens'] as $item): ?><option value="<?= (int) $item['id_servico'] ?>"><?= esc($item['nome']) ?></option><?php endforeach ?></select></div></div><button class="btn btn-primary" type="submit">Anexar</button></form></details><?php endif ?>
</div></div>
<div class="card"><div class="card-body"><details id="consumo"><summary class="h6 mb-0">Consumo de materiais <span class="text-muted small">(<?= count($ordem['consumos']) ?> registro(s))</span></summary><div class="mt-3"><p class="text-muted small">Registre o material utilizado, inclusive em cortesias. O consumo reduz o estoque sem acrescentar valor ao orçamento.</p><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Material</th><th>Quantidade</th><th>Registro</th><th></th></tr></thead><tbody><?php foreach ($ordem['consumos'] as $c): ?><tr><td><?= esc($c['material_nome']) ?><small class="d-block"><?= esc($c['observacoes']) ?></small></td><td><?= $medida($c['quantidade']) ?> <?= esc($c['unidade']) ?></td><td><?= $dataBr($c['created_at'], true) ?></td><td><?php if (! empty($c['estornado_at'])): ?><span class="text-muted small">Estornado: <?= esc($c['estorno_motivo']) ?></span><?php else: ?><details><summary class="small">Estornar</summary><form method="post" action="/ordensDeServicos/estornarConsumoAtendimento"><?= $hidden() ?><input type="hidden" name="id_saida" value="<?= (int) $c['id_saida'] ?>"><label class="small" for="motivo-consumo-<?= (int) $c['id_saida'] ?>">Motivo</label><input class="form-control form-control-sm mb-1" id="motivo-consumo-<?= (int) $c['id_saida'] ?>" name="motivo" required maxlength="512"><button class="btn btn-sm btn-outline-danger">Confirmar estorno</button></form></details><?php endif ?></td></tr><?php endforeach ?></tbody></table></div>
<?php if (! $cancelado): ?><form class="mt-3" method="post" action="/ordensDeServicos/consumirAtendimento"><?= $hidden() ?><?= $chave() ?><div class="row"><div class="form-group col-md-5"><label for="material-consumo">Material</label><select class="form-control" name="id_produto" id="material-consumo" required><option value="">Selecione</option><?php foreach ($materiais as $m): ?><option value="<?= (int) $m['id_produto'] ?>"><?= esc($m['nome']) ?> · disponível <?= $medida($m['quantidade']) ?> <?= esc($m['unidade']) ?></option><?php endforeach ?></select></div><div class="form-group col-md-2"><label for="quantidade-consumo">Quantidade</label><input class="form-control" id="quantidade-consumo" name="quantidade" inputmode="decimal" required placeholder="0,0000"></div><div class="form-group col-md-5"><label for="servico-consumo">Serviço / cortesia</label><select class="form-control" name="id_servico_os" id="servico-consumo"><option value="">Atendimento completo</option><?php foreach ($ordem['itens'] as $item): ?><option value="<?= (int) $item['id_servico'] ?>"><?= esc($item['nome']) ?><?= ! empty($item['cortesia']) ? ' (cortesia)' : '' ?></option><?php endforeach ?></select></div></div><div class="form-group"><label for="obs-consumo">Observação</label><input class="form-control" id="obs-consumo" name="observacoes" maxlength="512"></div><button class="btn btn-primary" type="submit">Registrar consumo</button></form><?php endif ?></div></details></div></div>
<div class="card"><div class="card-body"><details><summary class="h6 mb-0">Equipamentos e laudos <small class="text-muted">(opcional)</small></summary><div class="mt-3">
<?php $equipamentos = $ordem['equipamentos']; if (! $cancelado) $equipamentos[] = []; foreach ($equipamentos as $eq): $eqid = (int) ($eq['id_equipamento'] ?? 0); ?><details class="border rounded p-2 mb-2"><summary><?= esc($eq['equipamento'] ?? 'Adicionar equipamento') ?></summary><form class="mt-3" method="post" action="/ordensDeServicos/salvarEquipamentoAtendimento"><?= $hidden() ?><input type="hidden" name="versao" value="<?= (int) $ordem['versao'] ?>"><?php if ($eqid): ?><input type="hidden" name="id_equipamento" value="<?= $eqid ?>"><?php endif ?><fieldset <?= $cancelado ? 'disabled' : '' ?>><div class="row"><?php foreach (['equipamento' => 'Equipamento', 'marca' => 'Marca', 'modelo' => 'Modelo', 'serie' => 'Série'] as $key => $label): ?><div class="form-group col-md-3"><label for="eq-<?= $eqid ?>-<?= $key ?>"><?= $label ?></label><input class="form-control" id="eq-<?= $eqid ?>-<?= $key ?>" name="<?= $key ?>" value="<?= esc($eq[$key] ?? '', 'attr') ?>" maxlength="128" <?= $key === 'equipamento' ? 'required' : '' ?>></div><?php endforeach ?></div><div class="row"><?php foreach (['condicoes' => 'Condições', 'defeitos' => 'Defeitos', 'acessorios' => 'Acessórios', 'solucao' => 'Solução', 'laudo_tecnico' => 'Laudo técnico', 'termos_de_garantia' => 'Garantia'] as $key => $label): ?><div class="form-group col-md-6"><label for="eq-<?= $eqid ?>-<?= $key ?>"><?= $label ?></label><textarea class="form-control" id="eq-<?= $eqid ?>-<?= $key ?>" name="<?= $key ?>" maxlength="2048" rows="2"><?= esc($eq[$key] ?? '') ?></textarea></div><?php endforeach ?></div><?php if (! $cancelado): ?><button class="btn btn-primary" type="submit">Salvar equipamento</button><?php endif ?></fieldset></form><?php if ($eqid && ! $cancelado): ?><form class="mt-2" method="post" action="/ordensDeServicos/removerEquipamentoAtendimento"><?= $hidden() ?><input type="hidden" name="id_equipamento" value="<?= $eqid ?>"><button class="btn btn-sm btn-outline-danger" type="submit">Remover equipamento</button></form><?php endif ?></details><?php endforeach ?>
</div></details></div></div>
<div class="card"><div class="card-header"><h2 class="card-title">Histórico do atendimento</h2></div><div class="card-body"><ol class="pl-3 mb-0"><?php foreach ($ordem['historico'] as $h): ?><li class="mb-3"><strong><?= esc($h['status_novo'] && $h['status_novo'] !== $h['status_anterior'] ? (($statuses[$h['status_anterior']] ?? 'Início') . ' → ' . ($statuses[$h['status_novo']] ?? $h['status_novo'])) : ucfirst(str_replace('_', ' ', $h['evento']))) ?></strong><small class="text-muted d-block"><?= $dataBr($h['created_at'], true) ?> · <?= esc($h['usuario_nome'] ?: 'Usuário #' . $h['id_login']) ?></small><?php if (! empty($h['motivo'])): ?><div>Motivo: <?= nl2br(esc($h['motivo'])) ?></div><?php endif ?><?php if (! empty($h['observacoes'])): ?><div><?= nl2br(esc($h['observacoes'])) ?></div><?php endif ?></li><?php endforeach ?></ol><?php if (! $ordem['historico']): ?><p class="text-muted mb-0">Atendimento anterior ao histórico detalhado.</p><?php endif ?></div></div>
<div class="card"><div class="card-body"><details><summary class="text-muted">Cancelar ou enviar para Excluídos</summary><div class="row mt-3"><?php if (! $cancelado): ?><div class="col-md-7"><form method="post" action="/ordensDeServicos/statusAtendimento"><?= $hidden() ?><input type="hidden" name="status_operacional" value="cancelado"><label for="cancelar-motivo">Motivo do cancelamento</label><input class="form-control mb-2" id="cancelar-motivo" name="motivo" maxlength="512" required><button class="btn btn-outline-danger" type="submit">Cancelar atendimento</button></form></div><?php endif ?><div class="col-md-5"><p class="small">Enviar para Excluídos oculta o orçamento das listas. Ele poderá ser restaurado em até 30 dias.</p><form method="post" action="/ordensDeServicos/excluirAtendimento"><?= $hidden() ?><button class="btn btn-outline-secondary" type="submit">Enviar para Excluídos</button></form></div></div></details></div></div>
</div></section></div>
